const APP='mcq-simple-v3', DB='mcq-simple-db', VER=1;
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let dbp, imported=null, current=null, currentIndex=0, answered=false;
function db(){if(dbp)return dbp;dbp=new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{for(const n of ['quizzes','progress','imports'])if(!r.result.objectStoreNames.contains(n))r.result.createObjectStore(n,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});return dbp}
async function all(s){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(s).objectStore(s).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function get(s,id){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(s).objectStore(s).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function put(s,v){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(s,'readwrite').objectStore(s).put(v);r.onsuccess=()=>res(v);r.onerror=()=>rej(r.error)})}
async function del(s,id){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(s,'readwrite').objectStore(s).delete(id);r.onsuccess=res;r.onerror=()=>rej(r.error)})}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function nav(v){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v))}
async function home(){nav('home');const qs=await all('quizzes');const ps=await all('progress');$('#app').innerHTML=`<section class=hero><h1>MCQ STUDY</h1><p>Put in a PDF. Get usable MCQs. Fix only what needs fixing.</p><button id=start>Import a PDF</button></section><div class=stats><div><b>${qs.length}</b><span>Sources</span></div><div><b>${ps.filter(x=>x.wrong).length}</b><span>Wrong answers</span></div></div>`;$('#start').onclick=showImport}
function shell(title,body){$('#app').innerHTML=`<section class=card><div class=top><button class=back id=back>← Back</button><h1>${title}</h1></div>${body}</section>`;$('#back').onclick=home}
function showImport(){nav('import');shell('Import PDF',`<p class=muted>Choose your PDF. Text is extracted page-by-page, then the detector looks for questions and answer choices.</p><input id=file type=file accept=".pdf,application/pdf"><div id=importBox></div>`);$('#file').onchange=e=>startImport(e.target.files[0])}
const PDF='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/6.3.289/pdf.min.mjs';let pdfPromise;
async function pdfjs(){if(!pdfPromise)pdfPromise=import(PDF).then(m=>{m.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/6.3.289/pdf.worker.min.mjs';return m});return pdfPromise}
async function extract(file){const p=await pdfjs();const first=await file.slice(0,1024*1024).arrayBuffer();class R extends p.PDFDataRangeTransport{constructor(){super(file.size,new Uint8Array(first),false,file.name)}requestDataRange(a,b){file.slice(a,b).arrayBuffer().then(x=>this.onDataRange(a,new Uint8Array(x)))}}const pdf=await p.getDocument({range:new R(),rangeChunkSize:1024*1024,disableAutoFetch:true,disableStream:true,enableScripting:false}).promise;let raw='',pages=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),tc=await page.getTextContent(),items=(tc.items||[]).filter(x=>x.str?.trim()),rows=[];for(const it of items){const y=it.transform?.[5]||0;let row=rows.find(r=>Math.abs(r.y-y)<3);if(!row){row={y,items:[]};rows.push(row)}row.items.push(it)}rows.sort((a,b)=>b.y-a.y);const text=rows.map(r=>r.items.sort((a,b)=>(a.transform?.[4]||0)-(b.transform?.[4]||0)).map(x=>x.str.trim()).filter(Boolean).join(' ')).join('\n').trim();pages.push({page:n,text,ocr:text.replace(/\s/g,'').length<20});raw+=`\n===== PAGE ${n} =====\n${text||'[OCR NEEDED]'}\n`;$(`#importBox`).innerHTML=`<p class=muted>Reading page ${n} of ${pdf.numPages}…</p>`;page.cleanup?.();if(n%8===0)await new Promise(r=>setTimeout(r,0))}return{raw,pages}}
function answerKey(raw){const key=[],m=raw.match(/(?:^|\n)\s*(?:answer\s*key|answers?)\s*:?([\s\S]*)$/i);if(!m)return key;const re=/(?:^|\s)(?:Q(?:uestion)?\s*)?(\d+)\s*[.):\-]?\s*\(?([A-Da-d1-4])\)?(?=\s|$)/g;let x;while((x=re.exec(m[1])))key.push({n:Number(x[1]),a:/^[1-4]$/.test(x[2])?'ABCD'[+x[2]-1]:x[2].toUpperCase()});return key}
function parseMCQ(raw){raw=raw.replace(/===== PAGE \d+ =====/g,'\n').replace(/\[OCR NEEDED\]/g,'').replace(/\r/g,'').replace(/\u00a0/g,' ');const key=answerKey(raw),ai=raw.search(/(?:^|\n)\s*(?:answer\s*key|answers?)\s*:?/i);if(ai>=0)raw=raw.slice(0,ai);const qre=/(?:^|\s)(?:Q(?:uestion)?\s*\.?\s*#?\s*|Question\s+)?(\d{1,4})\s*[.)\-:]\s+/gi,starts=[...raw.matchAll(qre)],optRe=/(?:^|\s)(?:\(([A-Da-d])\)|([A-Da-d])[.)\-:])\s*/g;
 const make=(num,body,line)=>{body=body.replace(/\s+/g,' ').trim();let answer=null;const am=body.match(/\b(?:correct\s+)?answer\s*[:\-]?\s*\(?([A-Da-d1-4])\)?\b/i);if(am){answer=/^[1-4]$/.test(am[1])?'ABCD'[+am[1]-1]:am[1].toUpperCase();body=body.slice(0,am.index).trim()}let ms=[...body.matchAll(optRe)],chosen=null;for(let i=0;i<=ms.length-4;i++){if(ms.slice(i,i+4).map(m=>(m[1]||m[2]).toUpperCase()).join('')==='ABCD'){chosen=ms.slice(i,i+4);break}}const o={A:'',B:'',C:'',D:''};let q=body;if(chosen){q=body.slice(0,chosen[0].index).trim();chosen.forEach((m,i)=>{o[(m[1]||m[2]).toUpperCase()]=body.slice(m.index+m[0].length,chosen[i+1]?.index??body.length).trim()})}else{const nm=[...body.matchAll(/(?:^|\s)(?:\(([1-4])\)|([1-4])[.)\-:])\s*/g)];if(nm.length>=4){q=body.slice(0,nm[0].index).trim();nm.slice(0,4).forEach((m,i)=>o['ABCD'[i]]=body.slice(m.index+m[0].length,nm[i+1]?.index??body.length).trim())}}return{id:'q_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8),displayedNumber:num,question:q,options:o,correctAnswer:answer,sourceLine:line}};
 let out=[];if(starts.length){for(let i=0;i<starts.length;i++){const st=starts[i],en=starts[i+1]?.index??raw.length;out.push(make(Number(st[1]),raw.slice(st.index+st[0].length,en),raw.slice(0,st.index).split('\n').length))}}else{const joined=raw.replace(/\n+/g,' '),ms=[...joined.matchAll(optRe)];let pos=0;while(pos<ms.length){let k=-1;for(let i=pos;i<=ms.length-4;i++)if(ms.slice(i,i+4).map(m=>(m[1]||m[2]).toUpperCase()).join('')==='ABCD'){k=i;break}if(k<0)break;out.push(make(null,joined.slice(0,ms[k+4]?.index??joined.length),1));pos=k+4}}
 if(key.length===out.length)out.forEach((q,i)=>q.correctAnswer=key[i].a);else for(const q of out){const a=key.filter(x=>String(x.n)===String(q.displayedNumber));if(a.length===1&&!q.correctAnswer)q.correctAnswer=a[0].a}out.forEach(q=>{const miss=['A','B','C','D'].filter(k=>!q.options[k]);q.status=q.question&&miss.length===0&&q.correctAnswer?'READY':'REVIEW';q.diagnostic=q.status==='READY'?'Looks complete.':`${q.question?'':'Question text missing.'}${miss.length?' Missing '+miss.join(', ')+'.':''}${q.correctAnswer?'':' Correct answer not found.'}`});return out}
async function startImport(file){if(!file)return;$('#importBox').innerHTML='<p>Extracting…</p>';try{const r=await extract(file);imported={name:file.name.replace(/\.[^.]+$/,''),filename:file.name,raw:r.raw,pages:r.pages,questions:parseMCQ(r.raw)};await put('imports',{id:'imp_'+Date.now(),name:imported.name,filename:file.name,raw:r.raw,pages:r.pages});renderDetected()}catch(e){$('#importBox').innerHTML=`<p class=danger>${esc(e.message)}</p>`}}
function renderDetected(){nav('import');const qs=imported.questions,ready=qs.filter(q=>q.status==='READY').length,review=qs.length-ready;$('#app').innerHTML=`<section class=card><div class=top><button class=back id=back>← Back</button><h1>${esc(imported.name)}</h1></div><div class=detectStats><b>${qs.length}<small>detected</small></b><b>${ready}<small>ready</small></b><b>${review}<small>need checking</small></b></div><p class=muted>${ready?'Check the questions below, then add them to your Library.':'No complete MCQs were found yet. Edit the items below or inspect the extracted text.'}</p><div class=row><button id=add ${ready?'':'disabled'}>Add ${ready} ready MCQs to Library</button><button class=secondary id=txt>View extracted text</button></div></section><section id=cards></section>`;$('#back').onclick=showImport;$('#txt').onclick=showText;$('#add').onclick=addReady;const wrap=$('#cards');qs.forEach((q,i)=>{const el=document.createElement('article');el.className='question';el.innerHTML=`<div class=row><span class="pill ${q.status==='READY'?'ready':'review'}">${q.status}</span><span class=muted>Q ${q.displayedNumber??i+1}</span></div><label>Question<textarea data-i=${i} data-f=q>${esc(q.question)}</textarea></label><div class=opts>${['A','B','C','D'].map(k=>`<label>${k}<textarea data-i=${i} data-f=${k}>${esc(q.options[k])}</textarea></label>`).join('')}</div><label>Correct answer<select data-i=${i} data-f=answer><option value="">Not set</option>${['A','B','C','D'].map(k=>`<option ${q.correctAnswer===k?'selected':''}>${k}</option>`).join('')}</select></label><button class=secondary data-save=${i}>Save this question</button><span class=diag>${esc(q.diagnostic)}</span>`;wrap.append(el)});wrap.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>{const i=+b.dataset.save,q=qs[i];q.question=wrap.querySelector(`[data-i="${i}"][data-f=q]`).value;q.options={A:wrap.querySelector(`[data-i="${i}"][data-f=A]`).value,B:wrap.querySelector(`[data-i="${i}"][data-f=B]`).value,C:wrap.querySelector(`[data-i="${i}"][data-f=C]`).value,D:wrap.querySelector(`[data-i="${i}"][data-f=D]`).value};q.correctAnswer=wrap.querySelector(`[data-i="${i}"][data-f=answer]`).value||null;const miss=['A','B','C','D'].filter(k=>!q.options[k].trim());q.status=q.question.trim()&&!miss.length&&q.correctAnswer?'READY':'REVIEW';q.diagnostic=q.status==='READY'?'Ready.':'Still missing '+[...miss,...(!q.correctAnswer?['correct answer']:[])].join(', ');renderDetected();toast('Question saved')})}
function showText(){shell('Extracted text',`<p class=muted>Optional. This is what the PDF extractor saw.</p><textarea class=big id=raw>${esc(imported.raw)}</textarea><button id=back2>Back to detected MCQs</button>`);$('#back2').onclick=renderDetected}
async function addReady(){const qs=imported.questions.filter(q=>q.status==='READY').map(q=>({...q}));if(!qs.length)return;await put('quizzes',{id:'quiz_'+Date.now().toString(36),name:imported.name,filename:imported.filename,questions:qs,progress:{index:0,score:0},createdAt:Date.now()});toast(`Added ${qs.length} MCQs`);library()}
async function library(){nav('library');const qs=await all('quizzes');$('#app').innerHTML=`<section class=card><h1>Library</h1><p class=muted>Your sources stay separate. Resume where you stopped.</p></section>${qs.map(q=>`<section class=card><h2>${esc(q.name)}</h2><p>${q.questions.length} questions · ${Math.min(q.progress?.index||0,q.questions.length)} answered</p><div class=progress><i style="width:${q.questions.length?Math.min(100,(q.progress?.index||0)/q.questions.length*100):0}%"></i></div><div class=row><button data-play=${q.id}>${(q.progress?.index||0)>=q.questions.length?'Restart':'Resume'}</button><button class=danger data-del=${q.id}>Delete</button></div></section>`).join('')||'<section class=card><p>No quizzes yet.</p></section>`;document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>play(b.dataset.play));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this quiz?')){await del('quizzes',b.dataset.del);library()}})}
async function play(id){current=await get('quizzes',id);currentIndex=current.progress?.index||0;if(currentIndex>=current.questions.length){current.progress={index:0,score:0};currentIndex=0;await put('quizzes',current)}renderQuestion()}
function renderQuestion(){const q=current.questions[currentIndex];answered=false;$('#app').innerHTML=`<section class=card><div class=top><button class=back id=quit>← Library</button><span>${currentIndex+1} / ${current.questions.length}</span></div><div class=progress><i style="width:${currentIndex/current.questions.length*100}%"></i></div><h1>${esc(q.question)}</h1><div id=answers>${['A','B','C','D'].map(k=>`<button class=choice data-k=${k}>${k}. ${esc(q.options[k])}</button>`).join('')}</div><div id=feedback></div></section>`;$('#quit').onclick=library;document.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>answer(b.dataset.k))}
async function answer(k){if(answered)return;answered=true;const q=current.questions[currentIndex],ok=k===q.correctAnswer;if(ok)current.progress.score=(current.progress.score||0)+1;document.querySelectorAll('[data-k]').forEach(b=>{b.disabled=true;if(b.dataset.k===q.correctAnswer)b.classList.add('correct');if(b.dataset.k===k&&!ok)b.classList.add('wrong')});$('#feedback').innerHTML=`<p class=${ok?'success':'danger'}><b>${ok?'Correct':'Incorrect'}</b> · answer ${q.correctAnswer}</p><button id=next>${currentIndex+1<current.questions.length?'Next':'Finish'}</button>`;if(!ok)await put('progress',{id:current.id+':'+q.id,quizId:current.id,questionId:q.id,wrong:true});else{const p=await get('progress',current.id+':'+q.id);if(p){p.wrong=false;await put('progress',p)}}$('#next').onclick=async()=>{currentIndex++;current.progress.index=currentIndex;await put('quizzes',current);currentIndex>=current.questions.length?library():renderQuestion()}}
async function wrong(){nav('wrong');const [qs,ps]=await Promise.all([all('quizzes'),all('progress')]);const items=[];for(const p of ps.filter(x=>x.wrong)){const q=qs.find(q=>q.id===p.quizId)?.questions.find(x=>x.id===p.questionId);if(q)items.push({quizId:p.quizId,q})}$('#app').innerHTML=`<section class=card><h1>Wrong Answers</h1><p class=muted>Retry them without moving your Library position.</p></section>${items.map((x,i)=>`<section class=question><span class=pill>${esc(qs.find(q=>q.id===x.quizId).name)}</span><h2>${esc(x.q.question)}</h2>${['A','B','C','D'].map(k=>`<button class=choice data-w="${i}:${k}">${k}. ${esc(x.q.options[k])}</button>`).join('')}<div id=wf${i}></div></section>`).join('')||'<section class=card><p>No wrong answers.</p></section>`;items.forEach((x,i)=>document.querySelectorAll(`[data-w^="${i}:"]`).forEach(b=>b.onclick=async()=>{const k=b.dataset.w.split(':')[1],ok=k===x.q.correctAnswer;document.querySelectorAll(`[data-w^="${i}:"]`).forEach(z=>z.disabled=true);$(`#wf${i}`).innerHTML=`<p class=${ok?'success':'danger'}>${ok?'Correct. Removed.':'Still incorrect.'}</p>`;if(ok){const p=await get(x.quizId+':'+x.q.id);if(p){p.wrong=false;await put('progress',p)}}}))}
async function daily(){nav('daily');const qs=await all('quizzes'),ps=await all('progress'),pool=[];for(const q of qs)for(const x of q.questions){const p=ps.find(p=>p.quizId===q.id&&p.questionId===x.id);pool.push({q,x,priority:p?.wrong?0:1})}pool.sort((a,b)=>a.priority-b.priority);const chosen=pool.slice(0,10);$('#app').innerHTML=`<section class=card><h1>Daily Paper</h1><p class=muted>10 questions, prioritising your wrong answers.</p></section>${chosen.map((x,i)=>`<section class=question><div class=muted>${i+1}. ${esc(x.q.name)}</div><h2>${esc(x.x.question)}</h2>${['A','B','C','D'].map(k=>`<button class=choice data-d="${i}:${k}">${k}. ${esc(x.x.options[k])}</button>`).join('')}<div id=df${i}></div></section>`).join('')||'<section class=card><p>Your Library is empty.</p></section>`;chosen.forEach((x,i)=>document.querySelectorAll(`[data-d^="${i}:"]`).forEach(b=>b.onclick=()=>{const k=b.dataset.d.split(':')[1],ok=k===x.x.correctAnswer;document.querySelectorAll(`[data-d^="${i}:"]`).forEach(z=>z.disabled=true);$(`#df${i}`).innerHTML=`<p class=${ok?'success':'danger'}>${ok?'Correct':'Incorrect'} · answer ${x.x.correctAnswer}</p>`}))}
start();
async function start(){await db();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>({home,library,wrong,daily,import:showImport}[b.dataset.v])());await home()}
